---
title: "Project Start"
format: html
editor: visual
---

```{r}
library(haven)
library(tidyverse)
```

```{r}

dietFoods1 <- read_xpt('https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2021/DataFiles/DR1IFF_L.xpt') # each row is a different food or food combo for each person. could be useful if using food source as predictor?
  # potential predictors:
  # source of food
dietNuts1 <- read_xpt('https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2021/DataFiles/DR1TOT_L.xpt') # probably more useful as predictors. each row is a unique person's total intake. 
  # potential predictors:
  # how often add salt, all vars 30:50

examBP <- read_xpt('https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2021/DataFiles/BPXO_L.xpt') # blood pressures maybe good outcome?
examBM <- read_xpt('https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2021/DataFiles/BMX_L.xpt') # literal measurements. BMI useful?

quesHealthStatus <- read_xpt('https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2021/DataFiles/HSQ_L.xpt')
quesDBN <- read_xpt('https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2021/DataFiles/DBQ_L.xpt') # life history with food programs mostly. not useful
quesKidneyConds <- read_xpt('https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2021/DataFiles/KIQ_U_L.xpt') # low sample counts for any issues
quesMedConds <- read_xpt('https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2021/DataFiles/MCQ_L.xpt')
  # GREAT. potential outcome variables:
  # asthma, hay fever, arthritis, congestive heart failure, coronary heart disease, heart attack, stroke, thyroid problem, fatty liver, cancer

quesReprHlth <- read_xpt('https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2021/DataFiles/RHQ_L.xpt') # nah
```
