---
title: "Naive Bayes, LDA, and QDA"
output: html_document
date: "2025-02-28"
---

```{r}
library(tidyverse)
library(tidymodels)
library(discrim)
library(knitr)
library(haven)
```

```{r}
nutr <- read_xpt('Merged_Data.xpt')

nutr <- nutr |> 
  mutate(across(45:52, ~factor(.x, 
                               levels=c(1,2), 
                               labels=c('Yes','No'))))

nutrFilt <- list()

nutrNames <- names(nutr)

for (j in 45:52){
  nutrFilt[[j-44]] <- nutr |> 
    select(!(45:52), j)
}

names(nutrFilt) <- names(nutr)[45:52]

nutrFilt$asthma <- nutrFilt$asthma |> 
  filter(asthma %in% c('Yes','No'))

nutrFilt$hay_fever <- nutrFilt$hay_fever |> 
  filter(hay_fever %in% c('Yes','No'))

nutrFilt$arthritis <- nutrFilt$arthritis |> 
  filter(arthritis %in% c('Yes','No'))

nutrFilt$congestive_heart_failure <- nutrFilt$congestive_heart_failure |> 
  filter(congestive_heart_failure %in% c('Yes','No'))

nutrFilt$coronary_heart_disease <- nutrFilt$coronary_heart_disease |> 
  filter(coronary_heart_disease %in% c('Yes','No'))

nutrFilt$heart_attack <- nutrFilt$heart_attack |> 
  filter(heart_attack %in% c('Yes','No'))

nutrFilt$thyroid_problems <- nutrFilt$thyroid_problems |> 
  filter(thyroid_problems %in% c('Yes','No'))

nutrFilt$cancer <- nutrFilt$cancer |> 
  filter(cancer %in% c('Yes','No'))
```

```{r}
nbSpec <- naive_Bayes() |>
  set_mode('classification') |>
  set_engine('naivebayes') |>
  set_args(usekernel=F)

nutrRecs <- list(
  recipe(asthma ~ ., data=nutrFilt$asthma),
  recipe(hay_fever ~ ., data=nutrFilt$hay_fever),
  recipe(arthritis ~ ., data=nutrFilt$arthritis),
  recipe(congestive_heart_failure ~ ., data=nutrFilt$congestive_heart_failure),
  recipe(coronary_heart_disease ~ ., data=nutrFilt$coronary_heart_disease),
  recipe(heart_attack ~ ., data=nutrFilt$heart_attack),
  recipe(thyroid_problems ~ ., data=nutrFilt$thyroid_problems),
  recipe(cancer ~ ., data=nutrFilt$cancer)
)

nutrFolds <- list()
nutrWorks <- list()
nutrFits <- list()
nutrAccuracies <- list()

for (w in 1:length(nutrFilt)){
  nutrRecs[[w]] <- nutrRecs[[w]] |> 
    update_role(seqn,new_role='ID')

  nutrFolds[[w]] <- vfold_cv(nutrFilt[[w]],v=10)
  
  nutrWorks[[w]] <- workflow() |> 
    add_model(nbSpec) |> 
    add_recipe(nutrRecs[[w]])
  
  nutrFits[[w]] <- fit_resamples(nutrWorks[[w]],
                                 nutrFolds[[w]],
                                 metrics=metric_set(accuracy,roc_auc))
  
  nutrAccuracies[[w]] <- collect_metrics(nutrFits[[w]]) |> 
    select(!c(.estimator,.config,n)) |> 
    mutate(outcome=names(nutrFilt)[w],.before=1)
  
}

names(nutrAccuracies) <- names(nutrFits) <- names(nutrWorks) <- names(nutrFolds) <- names(nutrRecs) <- names(nutrFilt)

nutrAccuracies <- bind_rows(nutrAccuracies)
```

```{r}
nutrAccuracies |> 
  ggplot(aes(outcome,mean,fill=.metric))+
  geom_col(position='dodge')+
  geom_errorbar(aes(ymin = mean-std_err, ymax = mean+std_err), position = "dodge")

nutrAccuracies |> 
  filter(.metric=='accuracy') |> 
  rowwise() |> 
  mutate(mean=mean*100,std_err=std_err*100) |> 
  ggplot(aes(outcome,mean,fill=outcome))+
  geom_col(position='dodge')+
  geom_errorbar(aes(ymin = mean-std_err, ymax = mean+std_err), position = "dodge")+
  scale_fill_brewer(guide='none',palette = 'Dark2')+
  labs(y='Prediction accuracy (%)',x='Diagnosed with...',title='10-fold cross-validated prediction accuracy by diagnosis outcome')
```

```{r}
ldaSpec <- discrim_linear() |> 
  set_mode('classification') |>
  set_engine('MASS')

for (w in 1:length(nutrFilt)){
  nutrWorks[[w]] <- workflow() |> 
    add_model(ldaSpec) |> 
    add_recipe(nutrRecs[[w]])
  
  nutrFits[[w]] <- fit_resamples(nutrWorks[[w]],
                                 nutrFolds[[w]],
                                 metrics=metric_set(accuracy,roc_auc))
  
  nutrAccuracies[[w]] <- collect_metrics(nutrFits[[w]]) |> 
    dplyr::select(!c(.estimator,.config,n)) |> 
    mutate(outcome=names(nutrFilt)[w],.before=1)
  
}

nutrAccuracies |> 
  filter(.metric=='accuracy') |> 
  rowwise() |> 
  mutate(mean=mean*100,std_err=std_err*100) |> 
  ggplot(aes(outcome,mean,fill=outcome))+
  geom_col(position='dodge')+
  geom_errorbar(aes(ymin = mean-std_err, ymax = mean+std_err), position = "dodge")+
  scale_fill_brewer(guide='none',palette = 'Dark2')+
  labs(y='Prediction accuracy (%)',x='Diagnosed with...',title='10-fold cross-validated prediction accuracy by diagnosis outcome')
```
